### ISSUE TITLE
Example broken: object has no attribute 'reset

### ISSUE THREAD

**Issue by markusstraub** [eqasim-org/synpp#63]
The nyc_taxi example crashes because it calls the `progress.reset` function which is no longer present in the current version of synpp. (See `DownloadProgress` in `download.py`).

```AttributeError: 'ProgressContext' object has no attribute 'reset'```

**Comment by sebhoerl** [comment]
Thanks, I will have a look. The NYC example is not part if the unit tests, because it is rather large. So things may have changed in the meantime.
