### ISSUE TITLE
Default value of rerun_required when running a pipeline is False and cannot be changed

### ISSUE THREAD

**Issue by ainar** [eqasim-org/synpp#71]
Hello,

After upgrading from 1.3.1 (the version of synpp used for https://github.com/eqasim-org/ile-de-france) to 1.5.0 (the last version available today), I noticed a change of behavior.
The stages in the `run` section of the YML file are no longer "devalidated" if they are cached. I would like to always "devalidate" stages in the `run` section, but there is no parameter to do that from the YML file. Do I miss something?

I found that the `rerun_required` parameter of `run_pipeline` is set to `False` by default.
https://github.com/eqasim-org/synpp/blob/ad6e2c32525894ca17a428a0e7d8ada646cc9028/src/synpp/pipeline.py#L863
It confused me, as it is written:

> A *stage* is devalidated if ...
> - ... it is requested by the `run` call (and `rerun_required` is set to `True`, the default)

I understand that putting a stage name in the `run` section of the YML is not equivalent to requesting a `run` call on it. There is maybe something to clarify here.

Aina

**Comment by sebhoerl** [comment]
I think this is a mistake that might have slipped in. From my perspective, the default behaviour should be to devalidate them if they are in the `run` list.

**Comment by sebhoerl** [comment]
@davibicudo is to blame :stuck_out_tongue:

**Comment by sebhoerl** [comment]
Should rather be a config option with default `True`

**Comment by davibicudo** [comment]
Uh, yes, sorry about that, git blame won't allow me to escape this one 😁 . That was the intention, as correctly written in the documentation (the line was also edited by me, so clearly a slipped mistake). 
The issue happens when directly running via the CLI with the YAML file. I'll push the bugfix. 
A workaround for running via CLI could be (not tested):
```
python -c "from synpp import Synpp; Synpp.build_from_yml('config.yml').run_pipeline(rerun_required=True)"
```
.
