### ISSUE TITLE
Details of input data

### ISSUE THREAD

**Issue by buddih09** [eqasim-org/synpp#84]
Hi, Thank you for the nice repo. 
Could you please add more details about the input data requirements for running this pipeline? 
I imagine it is more or less the same as what is written under the "Synthetic population of Switzerland" GitLab repo. 
However, especially for an external user, more explicit information can be very helpful. For example, the GitLab repo documents the need for having structural_survey data, but it does not specify at which level (NUTS2, NUTS3, etc.) and what socio-demographic variables should the dataset contain. It is the same for other inputs as well. Do you think, it is possible to give a clearer picture on this?

**Comment by sebhoerl** [comment]
Hi, this repository has nothing to do with the actual implementation of a pipeline for population synthesis. It only provides the structure of defining a data pipeline and to connect the individual steps. For an example for an actual pipeline for population synthesis, check, for instance, Ile-de-France: https://github.com/eqasim-org/ile-de-france
