### ISSUE TITLE
What is the effect of `ephemeral` ?

### ISSUE THREAD

**Issue by Nitnelav** [eqasim-org/synpp#85]
I tried to understand it from code and tests but I'm struggling...

What are `ephemeral` stages ?

Cheers !

**Comment by sebhoerl** [comment]
They will not be cached. So if another stage depends on an ephemeral stage, that one will always need to be executed first before the main one is executed. The idea was mainly to especially remove the storage usage when we create 100 populations with different random seeds and then average over them, for instance.

**Comment by Nitnelav** [comment]
Perfect thanks !
